[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:srv]
command=/opt/venv/bin/python3 /app/bin/srv.py
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/supervisor/srv-stderr.log
stdout_logfile=/var/log/supervisor/srv-stdout.log

[program:proxy]
command=/opt/venv/bin/python3 /app/bin/proxy.py
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/supervisor/proxy-stderr.log
stdout_logfile=/var/log/supervisor/proxy-stdout.log

[program:geoproxy]
command=/opt/venv/bin/python3 /app/bin/geo-proxy.py
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/supervisor/geoproxy-stderr.log
stdout_logfile=/var/log/supervisor/geoproxy-stdout.log
